[package]
name = "nu_plugin_from_prometheus"
version = "0.1.0"
edition = "2021"

[dependencies]
nu-plugin = "0.79.0"
nu-protocol = { version = "0.79.0", features = ["plugin"] }
prometheus-parser = { git = "https://github.com/vectordotdev/vector" }
