[package]
name = "nu_plugin_from_prometheus"
version = "0.1.0"
edition = "2021"

[dependencies]
nu-plugin = "0.90.1"
nu-protocol = { version = "0.90.1", features = ["plugin"] }
prometheus-parser = { git = "https://github.com/vectordotdev/vector" }
